# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build account-manager`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t account-manager`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system account-manager && \
          adduser --system -G account-manager account-manager

COPY dist/account-manager account-manager
RUN chown -R account-manager:account-manager .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix account-manager --omit=dev -f install

CMD [ "node", "account-manager" ]
